### ISSUE TITLE
hello from bionode!

### ISSUE THREAD

**Issue by thejmazz** [nodestream/nodestream#20]
Hey nodestream!

I just came across this project, and it looks like a really good fit for [bionode-watermill](github.com/bionode/bionode-watermill). In fact, maybe their is even some (slight) overlap in our goals. (Right now we do our own checksum checking on files - and would need to do it on streams as well)

Just wanted to let you know, we have plans to integrate eventually into our project. Any help or suggestions would be greatly appreciated - see https://github.com/bionode/bionode-watermill/issues/46

:)

**Comment by robertrossmann** [comment]
Hello @thejmazz! That's nice to know, I'm happy that this project can help you in some way! Unfortunately I do not have much time to help you guys on integrating, but of course if you have any questions or suggestions feel free to open an issue here and I'll be happy to help.

Right now the API looks stable to me, I only have one change planned - in the `nodestream.registerTransform()`, I want developers to be able to provide their own name for the transform. Right now all transforms have their own `identity` names, but this is not very flexible and limits the transforms to be used only once in a pipeline.

Good luck and thanks for letting me know! 🍻
